import { createContext, ReactNode, useContext, useState } from "react";

type Language = "en" | "es" | "de" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const defaultContextValue: LanguageContextType = {
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
};

const LanguageContext = createContext<LanguageContextType>(defaultContextValue);

const en = {
  "general.continue": "Continue",
  "general.close": "Close",
  "general.cancel": "Cancel",

  "lang.selectLanguage": "SELECT LANGUAGE",
  "lang.chooseLanguage": "Choose your preferred language",
  "lang.selectLocation": "SELECT LOCATION",
  "lang.chooseCountry": "Which country are you from?",
  "lang.selectStatePlaceholder": "Select your state...",
  "country.us": "United States",
  "country.ca": "Canada",
  "country.de": "Germany",
  "country.uk": "England",

  "survey.question1": "Did you find everything that you were looking for in the store today?",
  "survey.question2": "Are you satisfied with your visit to the store today?",
  "survey.question3": "Did a store associate assist you today?",
  "survey.yes": "Yes",
  "survey.no": "No",

  "merch.categoryTitle": "WHAT TYPE OF MERCH ARE YOU LOOKING FOR?",
  "merch.jerseys": "Jerseys",
  "merch.hats": "Hats",
  "merch.shirts": "Shirts",
  "merch.accessories": "Accessories",

  "items.selectJersey": "SELECT YOUR JERSEY",
  "items.selectShirt": "SELECT YOUR SHIRT",
  "items.selectAccessory": "SELECT YOUR ACCESSORY",
  "items.selectHat": "SELECT YOUR HAT",
  "items.searchCategory": "Search {category}...",
  "items.selectSize": "SELECT YOUR SIZE",
  "items.addToCart": "Add to Cart",
  "items.addedToCart": "Added to Cart!",
  "items.nextPrompt": "What would you like to do next?",
  "items.goToCart": "Go to Cart",
  "items.continueShopping": "Continue Shopping",
  "items.cartButton": "Cart",

  "cart.title": "Your Cart",
  "cart.itemSingular": "item added",
  "cart.itemPlural": "items added",
  "cart.size": "Size",
  "cart.scanMessage": "Scan to complete your purchase & have your items shipped home.",
  "cart.backToItem": "Back to Item",
  "cart.selection": "Selection",
  "cart.discountTitle": "GET 15% OFF",
  "cart.discountSubtitle": "YOUR NEXT IN STORE PURCHASE",
  "cart.selectNewSize": "Select New Size",
  "cart.updateCart": "Update Cart",
  "cart.nextPrompt": "What would you like to do?",
  "cart.stayCheckout": "Stay in Cart & Finish Checkout",
  "cart.backToItemSelection": "Back to Item Selection",

  "discount.titleLine1": "Get 15% Off Your",
  "discount.titleLine2": "Next In Store Purchase",
  "discount.emailPrompt": "Please enter your email address",
  "discount.emailPlaceholder": "your@email.com",

  "search.title": "What merch were you looking for?",
  "search.placeholder": "Search jerseys, hats, shirts...",
  "search.empty": "Start typing to search all Jets merchandise",
  "search.noItems": "No items found for \"{query}\"",
  "search.selected": "Selected",
  "search.categoryJersey": "Jersey",
  "search.categoryHat": "Hat",
  "search.categoryShirt": "Shirt",
  "search.categoryAccessory": "Accessory",

  "feedback.title": "What Affected Your Shopping Experience?",
  "feedback.subtitle": "Please let us know what we can improve.",
  "feedback.option1": "I could not find the item I wanted",
  "feedback.option2": "The checkout process was difficult",
  "feedback.option3": "The wait time was too long",
  "feedback.option4": "I needed assistance and did not get any",
  "feedback.option5": "The associate was unfriendly",
  "feedback.option6": "Other",
  "feedback.submit": "Submit",
  "feedback.modalTitle": "Please tell us more",
  "feedback.modalPlaceholder": "Type your feedback here...",

  "rating.title": "How Would You Rate Your Associate Interaction?",
  "rating.subtitle": "Your feedback helps us improve.",
  "rating.satisfied": "Satisfied",
  "rating.neutral": "Neutral",
  "rating.dissatisfied": "Dissatisfied",
  "rating.submit": "Submit",

  "thankyou.title": "Thank You!",
  "thankyou.message": "Please check your email for your discount code.",
  "thankyou.countdown": "Survey will close in",
  "thankyou.seconds": "seconds",
};

const translations: Record<Language, Record<string, string>> = {
  en,
  es: {
    ...en,
    "general.continue": "Continuar",
    "general.close": "Cerrar",
    "general.cancel": "Cancelar",
    "lang.selectLanguage": "SELECCIONAR IDIOMA",
    "lang.chooseLanguage": "Elige tu idioma preferido",
    "lang.selectLocation": "SELECCIONAR UBICACION",
    "lang.chooseCountry": "De que pais eres?",
    "lang.selectStatePlaceholder": "Selecciona tu estado...",
    "country.us": "Estados Unidos",
    "country.ca": "Canada",
    "country.de": "Alemania",
    "country.uk": "Inglaterra",
    "survey.question1": "Encontraste todo lo que buscabas hoy en la tienda?",
    "survey.question2": "Estas satisfecho con tu visita a la tienda hoy?",
    "survey.question3": "Te ayudo hoy un asociado de la tienda?",
    "survey.yes": "Si",
    "survey.no": "No",
    "merch.categoryTitle": "QUE TIPO DE MERCANCIA BUSCAS?",
    "merch.jerseys": "Jerseys",
    "merch.hats": "Gorras",
    "merch.shirts": "Camisetas",
    "merch.accessories": "Accesorios",
    "items.selectJersey": "SELECCIONA TU JERSEY",
    "items.selectShirt": "SELECCIONA TU CAMISETA",
    "items.selectAccessory": "SELECCIONA TU ACCESORIO",
    "items.selectHat": "SELECCIONA TU GORRA",
    "items.searchCategory": "Buscar {category}...",
    "items.selectSize": "SELECCIONA TU TALLA",
    "items.addToCart": "Agregar al carrito",
    "items.addedToCart": "Agregado al carrito!",
    "items.nextPrompt": "Que quieres hacer ahora?",
    "items.goToCart": "Ir al carrito",
    "items.continueShopping": "Seguir comprando",
    "items.cartButton": "Carrito",
    "cart.title": "Tu carrito",
    "cart.itemSingular": "articulo agregado",
    "cart.itemPlural": "articulos agregados",
    "cart.size": "Talla",
    "cart.scanMessage": "Escanea para completar tu compra y recibir tus articulos en casa.",
    "cart.backToItem": "Volver a articulos",
    "cart.selection": "Seleccion",
    "cart.discountTitle": "15% DE DESCUENTO",
    "cart.discountSubtitle": "EN TU PROXIMA COMPRA EN TIENDA",
    "cart.selectNewSize": "Selecciona nueva talla",
    "cart.updateCart": "Actualizar carrito",
    "cart.nextPrompt": "Que quieres hacer?",
    "cart.stayCheckout": "Quedarse en el carrito y finalizar",
    "cart.backToItemSelection": "Volver a seleccion de articulos",
    "discount.titleLine1": "Obten 15% de descuento",
    "discount.titleLine2": "en tu proxima compra",
    "discount.emailPrompt": "Ingresa tu correo electronico",
    "discount.emailPlaceholder": "tu@email.com",
    "search.title": "Que mercancia estabas buscando?",
    "search.placeholder": "Buscar jerseys, gorras, camisetas...",
    "search.empty": "Empieza a escribir para buscar mercancia de los Jets",
    "search.noItems": "No se encontraron articulos para \"{query}\"",
    "search.selected": "Seleccionado",
    "search.categoryHat": "Gorra",
    "search.categoryShirt": "Camiseta",
    "search.categoryAccessory": "Accesorio",
    "feedback.title": "Que afecto tu experiencia de compra?",
    "feedback.subtitle": "Por favor dejanos saber que podemos mejorar.",
    "feedback.option1": "No pude encontrar el articulo que queria",
    "feedback.option2": "El proceso de pago fue dificil",
    "feedback.option3": "El tiempo de espera fue muy largo",
    "feedback.option4": "Necesitaba ayuda y no la recibi",
    "feedback.option5": "El asociado fue antipatico",
    "feedback.option6": "Otro",
    "feedback.submit": "Enviar",
    "feedback.modalTitle": "Por favor cuentanos mas",
    "feedback.modalPlaceholder": "Escribe tu comentario aqui...",
    "rating.title": "Como calificarias tu interaccion con el asociado?",
    "rating.subtitle": "Tu opinion nos ayuda a mejorar.",
    "rating.satisfied": "Satisfecho",
    "rating.neutral": "Neutral",
    "rating.dissatisfied": "Insatisfecho",
    "rating.submit": "Enviar",
    "thankyou.title": "Gracias!",
    "thankyou.message": "Revisa tu correo electronico para obtener tu codigo de descuento.",
    "thankyou.countdown": "La encuesta se cerrara en",
    "thankyou.seconds": "segundos",
  },
  de: {
    ...en,
    "general.continue": "Weiter",
    "general.close": "Schliessen",
    "general.cancel": "Abbrechen",
    "lang.selectLanguage": "SPRACHE AUSWAHLEN",
    "lang.chooseLanguage": "Waehle deine bevorzugte Sprache",
    "lang.selectLocation": "STANDORT AUSWAHLEN",
    "lang.chooseCountry": "Aus welchem Land kommst du?",
    "lang.selectStatePlaceholder": "Waehle deinen Bundesstaat...",
    "country.us": "Vereinigte Staaten",
    "country.ca": "Kanada",
    "country.de": "Deutschland",
    "country.uk": "England",
    "survey.question1": "Hast du heute alles gefunden, wonach du im Store gesucht hast?",
    "survey.question2": "Bist du mit deinem heutigen Store-Besuch zufrieden?",
    "survey.question3": "Hat dir heute ein Store-Mitarbeiter geholfen?",
    "survey.yes": "Ja",
    "survey.no": "Nein",
    "merch.categoryTitle": "WELCHE ART VON MERCH SUCHST DU?",
    "merch.jerseys": "Trikots",
    "merch.hats": "Muetzen",
    "merch.shirts": "Shirts",
    "merch.accessories": "Accessoires",
    "items.selectJersey": "WAEHLE DEIN TRIKOT",
    "items.selectShirt": "WAEHLE DEIN SHIRT",
    "items.selectAccessory": "WAEHLE DEIN ACCESSOIRE",
    "items.selectHat": "WAEHLE DEINE MUETZE",
    "items.searchCategory": "{category} suchen...",
    "items.selectSize": "WAEHLE DEINE GROESSE",
    "items.addToCart": "In den Warenkorb",
    "items.addedToCart": "Zum Warenkorb hinzugefuegt!",
    "items.nextPrompt": "Was moechtest du als Naechstes tun?",
    "items.goToCart": "Zum Warenkorb",
    "items.continueShopping": "Weiter einkaufen",
    "items.cartButton": "Warenkorb",
    "cart.title": "Dein Warenkorb",
    "cart.itemSingular": "Artikel hinzugefuegt",
    "cart.itemPlural": "Artikel hinzugefuegt",
    "cart.size": "Groesse",
    "cart.scanMessage": "Scanne, um den Kauf abzuschliessen und deine Artikel nach Hause liefern zu lassen.",
    "cart.backToItem": "Zurueck zur",
    "cart.selection": "Auswahl",
    "cart.discountTitle": "15% RABATT",
    "cart.discountSubtitle": "AUF DEINEN NAECHSTEN EINKAUF IM STORE",
    "cart.selectNewSize": "Neue Groesse waehlen",
    "cart.updateCart": "Warenkorb aktualisieren",
    "cart.nextPrompt": "Was moechtest du tun?",
    "cart.stayCheckout": "Im Warenkorb bleiben und abschliessen",
    "cart.backToItemSelection": "Zurueck zur Artikelauswahl",
    "discount.titleLine1": "Erhalte 15% Rabatt",
    "discount.titleLine2": "auf deinen naechsten Einkauf",
    "discount.emailPrompt": "Bitte gib deine E-Mail-Adresse ein",
    "discount.emailPlaceholder": "deine@email.com",
    "search.title": "Nach welchem Merch hast du gesucht?",
    "search.placeholder": "Trikots, Muetzen, Shirts suchen...",
    "search.empty": "Beginne zu tippen, um Jets-Merch zu suchen",
    "search.noItems": "Keine Artikel gefunden fuer \"{query}\"",
    "search.selected": "Ausgewaehlt",
    "search.categoryJersey": "Trikot",
    "search.categoryHat": "Muetze",
    "search.categoryShirt": "Shirt",
    "search.categoryAccessory": "Accessoire",
    "feedback.title": "Was hat dein Einkaufserlebnis beeinflusst?",
    "feedback.subtitle": "Bitte sag uns, was wir verbessern koennen.",
    "feedback.option1": "Ich konnte den gesuchten Artikel nicht finden",
    "feedback.option2": "Der Bezahlvorgang war schwierig",
    "feedback.option3": "Die Wartezeit war zu lang",
    "feedback.option4": "Ich brauchte Hilfe und bekam keine",
    "feedback.option5": "Der Mitarbeiter war unfreundlich",
    "feedback.option6": "Andere",
    "feedback.submit": "Senden",
    "feedback.modalTitle": "Bitte erzaehle uns mehr",
    "feedback.modalPlaceholder": "Schreibe dein Feedback hier...",
    "rating.title": "Wie bewertest du den Kontakt mit dem Mitarbeiter?",
    "rating.subtitle": "Dein Feedback hilft uns, besser zu werden.",
    "rating.satisfied": "Zufrieden",
    "rating.neutral": "Neutral",
    "rating.dissatisfied": "Unzufrieden",
    "rating.submit": "Senden",
    "thankyou.title": "Danke!",
    "thankyou.message": "Bitte pruefe deine E-Mail auf deinen Rabattcode.",
    "thankyou.countdown": "Die Umfrage schliesst in",
    "thankyou.seconds": "Sekunden",
  },
  pt: {
    ...en,
    "general.continue": "Continuar",
    "general.close": "Fechar",
    "general.cancel": "Cancelar",
    "lang.selectLanguage": "SELECIONE O IDIOMA",
    "lang.chooseLanguage": "Escolha seu idioma preferido",
    "lang.selectLocation": "SELECIONE O LOCAL",
    "lang.chooseCountry": "De qual pais voce e?",
    "lang.selectStatePlaceholder": "Selecione seu estado...",
    "country.us": "Estados Unidos",
    "country.ca": "Canada",
    "country.de": "Alemanha",
    "country.uk": "Inglaterra",
    "survey.question1": "Voce encontrou tudo que procurava hoje na loja?",
    "survey.question2": "Voce ficou satisfeito com sua visita hoje?",
    "survey.question3": "Um atendente da loja ajudou voce hoje?",
    "survey.yes": "Sim",
    "survey.no": "Nao",
    "merch.categoryTitle": "QUE TIPO DE PRODUTO VOCE PROCURA?",
    "merch.jerseys": "Camisas",
    "merch.hats": "Bones",
    "merch.shirts": "Camisetas",
    "merch.accessories": "Acessorios",
    "items.selectJersey": "SELECIONE SUA CAMISA",
    "items.selectShirt": "SELECIONE SUA CAMISETA",
    "items.selectAccessory": "SELECIONE SEU ACESSORIO",
    "items.selectHat": "SELECIONE SEU BONE",
    "items.searchCategory": "Buscar {category}...",
    "items.selectSize": "SELECIONE O TAMANHO",
    "items.addToCart": "Adicionar ao carrinho",
    "items.addedToCart": "Adicionado ao carrinho!",
    "items.nextPrompt": "O que voce quer fazer agora?",
    "items.goToCart": "Ir para o carrinho",
    "items.continueShopping": "Continuar comprando",
    "items.cartButton": "Carrinho",
    "cart.title": "Seu carrinho",
    "cart.itemSingular": "item adicionado",
    "cart.itemPlural": "itens adicionados",
    "cart.size": "Tamanho",
    "cart.scanMessage": "Escaneie para concluir sua compra e receber seus itens em casa.",
    "cart.backToItem": "Voltar aos itens",
    "cart.selection": "Selecao",
    "cart.discountTitle": "15% DE DESCONTO",
    "cart.discountSubtitle": "NA SUA PROXIMA COMPRA NA LOJA",
    "cart.selectNewSize": "Selecionar novo tamanho",
    "cart.updateCart": "Atualizar carrinho",
    "cart.nextPrompt": "O que voce quer fazer?",
    "cart.stayCheckout": "Ficar no carrinho e finalizar",
    "cart.backToItemSelection": "Voltar para selecao de itens",
    "discount.titleLine1": "Ganhe 15% de desconto",
    "discount.titleLine2": "na sua proxima compra",
    "discount.emailPrompt": "Digite seu e-mail",
    "discount.emailPlaceholder": "seu@email.com",
    "search.title": "Que produto voce estava procurando?",
    "search.placeholder": "Buscar camisas, bones, camisetas...",
    "search.empty": "Comece a digitar para buscar produtos dos Jets",
    "search.noItems": "Nenhum item encontrado para \"{query}\"",
    "search.selected": "Selecionado",
    "search.categoryJersey": "Camisa",
    "search.categoryHat": "Bone",
    "search.categoryShirt": "Camiseta",
    "search.categoryAccessory": "Acessorio",
    "feedback.title": "O que afetou sua experiencia de compra?",
    "feedback.subtitle": "Conte para nos o que podemos melhorar.",
    "feedback.option1": "Nao encontrei o item que queria",
    "feedback.option2": "O processo de pagamento foi dificil",
    "feedback.option3": "O tempo de espera foi longo demais",
    "feedback.option4": "Precisei de ajuda e nao recebi",
    "feedback.option5": "O atendente foi pouco cordial",
    "feedback.option6": "Outro",
    "feedback.submit": "Enviar",
    "feedback.modalTitle": "Conte mais para nos",
    "feedback.modalPlaceholder": "Digite seu feedback aqui...",
    "rating.title": "Como voce avaliaria a interacao com o atendente?",
    "rating.subtitle": "Seu feedback nos ajuda a melhorar.",
    "rating.satisfied": "Satisfeito",
    "rating.neutral": "Neutro",
    "rating.dissatisfied": "Insatisfeito",
    "rating.submit": "Enviar",
    "thankyou.title": "Obrigado!",
    "thankyou.message": "Verifique seu e-mail para receber seu codigo de desconto.",
    "thankyou.countdown": "A pesquisa sera encerrada em",
    "thankyou.seconds": "segundos",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => translations[language]?.[key] || translations.en[key] || key;

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
